name: news_sport_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  buttons_tabbar: ^1.3.8
  carousel_slider: ^4.2.1
  custom_sliding_segmented_control: ^1.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  gap: ^3.0.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  image_picker: ^1.0.7
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
